database:
    url: jdbc:mysql://localhost:3306/cms?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

server:
    port: 8889

auth2:
    githubClientId: c10fd104be25fa95bcc4
    
logging.level.org.jooq: DEBUG